---
:protocolo_produto: !str
  str: B8C3DD94-C8EC-4469-9B58-9698A35D09E7
  attributes: {}
:acao: !str
  str: aieManutencao
  attributes: {}
:codigo_produto_abacos: !str
  str: '1'
  attributes: {}
:codigo_produto: !str
  str: '10'
  attributes: {}
:codigo_produto_pai: !!null 
:codigo_barras: !str
  str: '0000000000001'
  attributes: {}
:tipo_produto: !str
  str: tpreProduto
  attributes: {}
:nome_produto: !str
  str: Sandália com Flor de couro Coral
  attributes: {}
:descricao: !!null 
:codigo_marca: !str
  str: '2'
  attributes: {}
:codigo_fabricante: !!null 
:codigo_classe: !str
  str: '2'
  attributes: {}
:codigo_familia: !str
  str: '2'
  attributes: {}
:codigo_grupo: !str
  str: '2'
  attributes: {}
:codigo_sub_grupo: !str
  str: '2'
  attributes: {}
:peso: !str
  str: '0.6'
  attributes: {}
:comprimento: !str
  str: '29.5'
  attributes: {}
:largura: !str
  str: '25'
  attributes: {}
:espessura: !str
  str: '10.5'
  attributes: {}
:qtde_por_embalagem: !str
  str: '1'
  attributes: {}
:qtde_minima_estoque: !str
  str: '0'
  attributes: {}
:qtde_maxima_estoque: !str
  str: '0'
  attributes: {}
:unidade_medida_nome: !str
  str: UNIDADE
  attributes: {}
:unidade_medida_abrev: !str
  str: UN
  attributes: {}
:unidade_medida_quilo: false
:produto_tem_filhos: true
:prazo_entrega_dias: !str
  str: '0'
  attributes: {}
:campo_cfg001: !!null 
:campo_cfg002: !!null 
:campo_cfg003: !!null 
:campo_cfg004: !!null 
:campo_cfg005: !!null 
:campo_cfg006: !!null 
:campo_cfg007: !!null 
:campo_cfg008: !!null 
:campo_cfg009: !!null 
:campo_cfg010: !!null 
:campo_cfg011: !!null 
:campo_cfg012: !!null 
:campo_cfg013: !!null 
:campo_cfg014: !!null 
:campo_cfg015: !!null 
:campo_cfg016: !!null 
:campo_cfg017: !!null 
:campo_cfg018: !!null 
:campo_cfg019: !!null 
:campo_cfg020: !!null 
:campo_cfg_int001: !!null 
:campo_cfg_int002: !!null 
:campo_cfg_int003: !!null 
:campo_cfg_int004: !!null 
:campo_cfg_int005: !!null 
:campo_cfg_int006: !!null 
:campo_cfg_int007: !!null 
:campo_cfg_int008: !!null 
:campo_cfg_int009: !!null 
:campo_cfg_int010: !!null 
:campo_cfg_int011: !!null 
:campo_cfg_int012: !!null 
:campo_cfg_int013: !!null 
:campo_cfg_int014: !!null 
:campo_cfg_int015: !!null 
:campo_cfg_int016: !!null 
:campo_cfg_int017: !!null 
:campo_cfg_int018: !!null 
:campo_cfg_int019: !!null 
:campo_cfg_int020: !!null 
:campo_cfg_int021: !!null 
:campo_cfg_int022: !!null 
:campo_cfg_int023: !!null 
:campo_cfg_int024: !!null 
:campo_cfg_int025: !!null 
:campo_cfg_int026: !!null 
:campo_cfg_int027: !!null 
:campo_cfg_int028: !!null 
:campo_cfg_int029: !!null 
:campo_cfg_int030: !!null 
:cfop_nao_contribuinte: !str
  str: '0'
  attributes: {}
:cfop_contribuinte: !str
  str: '0'
  attributes: {}
:unidade_tributavel: !str
  str: '0'
  attributes: {}
:custo_do_produto: !str
  str: '0'
  attributes: {}
:codigo_externo_fornecedor: !!null 
:descritor_simples:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200001'
      attributes: {}
    :descricao: !str
      str: Operação "Listar os descritores simples associados ao produto" efetuada
        com sucesso.
      attributes: {}
    :tipo: !str
      str: tdreSucesso
      attributes: {}
  :rows:
    :dados_descritor_simples:
    - :codigo_interno: !str
        str: '3'
        attributes: {}
      :numero: !str
        str: '1'
        attributes: {}
      :descricao: !str
        str: Natural
        attributes: {}
    - :codigo_interno: !str
        str: '3'
        attributes: {}
      :numero: !str
        str: '2'
        attributes: {}
      :descricao: !str
        str: Palm sint. Ouro light
        attributes: {}
:descritor_pre_definido:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200001'
      attributes: {}
    :descricao: !str
      str: Operação "Listar os descritores pré-definidos associados ao produto" efetuada
        com sucesso.
      attributes: {}
    :tipo: !str
      str: tdreSucesso
      attributes: {}
  :rows:
    :dados_descritor_pre_definido:
      :codigo_interno: !str
        str: '1'
        attributes: {}
      :numero: !str
        str: '1'
        attributes: {}
      :descricao: !str
        str: Couro Gergelim
        attributes: {}
      :grupo_codigo: !str
        str: '1'
        attributes: {}
      :grupo_nome: !str
        str: ! 'COR                                               '
        attributes: {}
:caracteristicas_complementares:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200001'
      attributes: {}
    :descricao: !str
      str: Operação "Listar as caracteristicas complementares associadas ao produto"
        efetuada com sucesso.
      attributes: {}
    :tipo: !str
      str: tdreSucesso
      attributes: {}
  :rows:
    :dados_caracteristicas_complementares:
      :codigo_interno: !str
        str: '1'
        attributes: {}
      :tipo_codigo: !str
        str: '1'
        attributes: {}
      :tipo_nome: !str
        str: ! 'DESCRIÇÃO LONGA                                   '
        attributes: {}
      :tipo_grupo_codigo: !str
        str: '1'
        attributes: {}
      :tipo_grupo_nome: !str
        str: ! 'DESCRIÇÕES PARA O SITE                            '
        attributes: {}
      :texto: !str
        str: casual
        attributes: {}
      :nr_config_interface: !str
        str: '0'
        attributes: {}
:produtos_substitutos:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200003'
      attributes: {}
    :descricao: !str
      str: OK, porém não há dados.
      attributes: {}
    :tipo: !str
      str: tdreSucessoSemDados
      attributes: {}
  :rows:
    :dados_produtos_substitutos:
      :codigo_substituto: !!null 
:categorias_do_site:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200003'
      attributes: {}
    :descricao: !str
      str: OK, porém não há dados.
      attributes: {}
    :tipo: !str
      str: tdreSucessoSemDados
      attributes: {}
  :rows:
    :dados_categorias_do_site:
      :codigo_categoria: !str
        str: '0'
        attributes: {}
      :codigo_categoria_pai: !str
        str: '0'
        attributes: {}
:produtos_personalizacao:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200003'
      attributes: {}
    :descricao: !str
      str: OK, porém não há dados.
      attributes: {}
    :tipo: !str
      str: tdreSucessoSemDados
      attributes: {}
  :rows:
    :dados_produtos_personalizacao:
      :classificacao_personalizacao: !str
        str: tpceNenhuma
        attributes: {}
      :codigo_produto_personalizacao: !!null 
      :codigo_produto_personalizacao_pai: !!null 
      :produto_personalizacao_ligacao: !str
        str: tptleIndefinido
        attributes: {}
:componentes_kit:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200003'
      attributes: {}
    :descricao: !str
      str: OK, porém não há dados.
      attributes: {}
    :tipo: !str
      str: tdreSucessoSemDados
      attributes: {}
  :rows:
    :dados_componentes_kit:
      :codigo_produto_componente: !!null 
      :quantidade: !str
        str: '0'
        attributes: {}
      :descritor_pre_definido1: !!null 
      :descritor_pre_definido2: !!null 
      :descritor_pre_definido3: !!null 
      :codigo_descritor_pre_definido1: !!null 
      :codigo_descritor_pre_definido2: !!null 
      :codigo_descritor_pre_definido3: !!null 
      :descritor_simples1: !!null 
      :descritor_simples2: !!null 
      :descritor_simples3: !!null 
:produtos_associados:
  :versao_web_service: !str
    str: 5.0B.0057
    attributes: {}
  :resultado_operacao:
    :codigo: !str
      str: '200003'
      attributes: {}
    :descricao: !str
      str: OK, porém não há dados.
      attributes: {}
    :tipo: !str
      str: tdreSucessoSemDados
      attributes: {}
  :rows:
    :dados_produtos_associados:
      :codigo_produto_abacos: !!null 
      :codigo_produto: !!null 
      :codigo_barras: !!null 
      :ordem_associacao: !!null 
      :tipo_associacao: !!null 
      :tipo_associacao_nome: !!null 
      :tipo_categoria: !!null 
      :tipo_categoria_nome: !!null 
:descricao_classe: !str
  str: ! 'Jóia                                              '
  attributes: {}
:descricao_marca: !str
  str: ! 'DCM                                               '
  attributes: {}
:descricao_familia: !str
  str: ! 'Sandália                                          '
  attributes: {}
:descricao_grupo: !str
  str: ! 'baixo                                             '
  attributes: {}
:descricao_subgrupo: !str
  str: ! 'SUB-GRUPO DE PRODUTOS                             '
  attributes: {}
:codigo_categoria_fiscal: !str
  str: '1'
  attributes: {}
:codigo_classificacao_fiscal: !str
  str: '1'
  attributes: {}
:classificacao_fiscal: !str
  str: '6403200   '
  attributes: {}
:dias_garantia: !str
  str: '0'
  attributes: {}
:pode_ser_brinde: false
:tipo_rastreabilidade: !str
  str: '0'
  attributes: {}
:tipo_controle_estoque: !str
  str: tceeControla
  attributes: {}
:produto_kit: false
:efetuar_check_out: true
:descricao_nota_fiscal: false
:classificacao_personalizacao: !str
  str: tpceNenhuma
  attributes: {}
:nao_imprimir_etq_entrada: false
