development:
  environment: "staging"
  IntegrationId: "10"
  CustomerId: "30"
  AffiliationId: "J0154272070001140000017597"
  AffiliationPassword: "o1q2c3m4l5m6c7d8"
  username: "rayban"
  password: "5b703a84b4"

test:
  environment: "staging"
  IntegrationId: "{YOUR_INTEGRATION_ID_ON_ACCESSTAGE}"
  CustomerId: "{YOUR_CUSTOMER_ID_ON_ACCESSTAGE}"
  AffiliationId: "{YOUR_AFFILIATION_ID_ON_ACCESSTAGE}"
  AffiliationPassword: "{YOUR_AFFILIATION_PASSWORD_ON_ACCESSTAGE}"
  username: "username"
  password: "password"

production:
  environment: "production"
  IntegrationId: "{YOUR_INTEGRATION_ID_ON_ACCESSTAGE}"
  CustomerId: "{YOUR_CUSTOMER_ID_ON_ACCESSTAGE}"
  AffiliationId: "{YOUR_AFFILIATION_ID_ON_ACCESSTAGE}"
  AffiliationPassword: "{YOUR_AFFILIATION_PASSWORD_ON_ACCESSTAGE}"
  username: "username"
  password: "password"
