cielo:
  visa: :cielo_visa
  mastercard: :cielo_mastercard
  americanexpress: :cielo_amex
  diners: :cielo_diners
  hipercard: :sitef_hipercard
  aura: :sitef_aura

redecard:
  visa: :redecard_visa
  mastercard: :redecard_mastercard
  americanexpress: :sitef_amex
  diners: :redecard_diners
  hipercard: :sitef_hipercard
  aura: :sitef_aura
