default: &default
  entity_code: "2524D4FD-80FF-44B6-BF1E-9423A8E6BA69"
  environment: "homolog"

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default