default: &default
  aws_access_key_id: 'AKIAJ2WH3XLYA24UTAJQ'
  aws_secret_access_key: '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'

production:
  << *default
  fog_directory: 'cdn-app.olook.com.br'

staging:
  << *default
  fog_directory: 'cdn-app-staging.olook.com.br'

development:
  << *default
  fog_directory: 'cdn-app-staging.olook.com.br'
