default: &default
  :site: http://api.9f01a855c4ef6.olook.mailee.me
  :welcome:
    :title: Welcome
    :subject: __member_name__, seja bem vinda! Seu cadastro foi feito com sucesso!
    :from_name: olook
    :from_email: bemvinda@my.olookmail.com.br
    :template_id: 9481
  :invite:
    :title: Invite
    :subject: __inviter_name__ te convidou para a olook!
    :from_name: olook
    :from_email: vip@o.conviteolook.com.br
    :template_id: 9506

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
