-
  type: 'CreditCard'
  name: 'Cartão de crédito'
  percentage: 0
-
  type: 'Debit'
  name: 'Débito'
  percentage: 0
-
  type: 'Billet'
  name: 'Boleto'
  percentage: 2
-
  type: 'MercadoPago'
  name: 'Mercado Pago'
  percentage: 2
