types:
  credit_card:
    name: 'Cartão de crédito'
    percentage: 0
    description: "TPPPPPPPP"
  debit:
    name: 'Débito'
    percentage: 0
    description: "TPPPPPPPP"
  billet:
    name: 'Boleto'
    percentage: 2
    description: "TPPPPPPPP"
  mercado_pago:
    name: 'Mercado Pago'
    percentage: 2
    description: "TPPPPPPPP"
