update_inventory:
  cron: "*/5 * * * *"
  class: Abacos::UpdateInventory
  queue: inventory
  description: "Atualiza o Inventario"

update_status:
  cron: "*/5 * * * *"
  class: Abacos::UpdateOrderStatus
  queue: order_status
  description: "Atualiza o status dos Pedidos"

send_in_cart_email:
  cron: "0 20 * * *"
  class: SendInCartEmailWorker
  queue: send_in_cart_email
  description: "Dispara emails para carrinhos abandonados"

marketing_uploader:
  cron: "0 2 * * *"
  class: MarketingUploaderWorker
  queue: marketing_uploader
  description: "Cria arquivo de importação para allinemail"

send_billet_reminder:
  cron: "0 5 * * 1-5"
  class: SendBilletReminderWorker
  queue: send_billet_reminder
  description: "Dispara emails de aviso p/ vencimento do boleto"

send_enabled_credits_notification:
  cron: "0 0 1 * *"
  class: SendEnabledCreditsNotificationWorker
  queue: notification_sender
  description: "Dispara emails avisando que os créditos de fidelidade estão disponíveis"

# TODO: CHANGE BACK TO 23 AFTER 23/09/2012
send_seven_days_to_expiration_warning:
  cron: "35 15 26 * *"
  class: SendExpirationWarningWorker
  queue: notification_sender
  description: "Dispara emails avisando que os créditos de fidelidade irão expirar"

send_one_day_to_expiration_warning:
  cron: "1 0 L * *"
  class: SendExpirationTomorrowWarningWorker
  queue: notification_sender
  description: "Dispara emails avisando que os créditos de fidelidade irão expirar amanhã"

