regenerate_html_sitemap:
  cron: "0 */6 * * *"
  class: SitemapWorker
  queue: low
  description: "Gera sitemap infos"

update_birthday_base:
  cron: "0 5 * * *"
  class: MarketingBaseUploaderWorker
  queue: low
  description: "Atualiza a base de aniversariantes na ExactTarget"

update_sitemap:
  cron: "0 3 * * *"
  class: SitemapWorker
  queue: low
  description: "Atualiza o sitemap"

index_suggested_terms:
  cron: "0 */6 * * *"
  class: ProductSearchWorker
  queue: low
  description: "Indexa os termos sugeridos para buscas"

index_products_for_searching:
  cron: "0 */3 * * *"
  class: IndexProductsWorker
  queue: low
  description: "Gera a base (arquivo .sdf) para a busca e faz o upload para amazon CloudSearch"

send_orders_alert:
  cron: "35 * * * *"
  class: SendOrderAlertWorker
  queue: low
  description: "Envia email avisando pedidos que precisam ser analizados com mais atencao"

update_ses_info:
  cron: "* 22 * * *"
  class: SaveSesInfoWorker
  queue: low
  description: "Atualiza a tabela ses com as informações "

update_inventory:
  cron: "*/45 * * * *"
  class: Abacos::UpdateInventory
  queue: low
  description: "Atualiza o Inventario"

update_order_status:
  cron: "*/30 * * * *"
  class: Abacos::UpdateOrderStatus
  queue: low
  description: "Atualiza o status dos Pedidos"

update_status:
  cron: "*/15 * * * *"
  class: ProcessPaymentCallbacksWorker
  queue: low
  description: "Processa callbacks de Pagamento Moip"

update_braspag_responses:
  cron: "*/15 * * * *"
  class: ProcessBraspagResponsesWorker
  queue: low
  description: "Processa respostas de pagamento Braspag"

csv_for_all_in:
  cron: "0 2 * * *"
  class: MultiWorkersProcessMaster
  queue: low
  args:
    - MktBaseGenerator
  description: "Cria arquivo de importação para allinemail"

# userbase_with_auth_token_and_credits:
#   cron: "0 2 * * *"
#   class: MarketingUploaderWorker
#   queue: low
#   args:
#     - userbase_with_auth_token_and_credits
#     - basegeral_novos_usuarios.csv
#     - false
#   description: "Cria arquivo de importação para allinemail com os usuarios criados a partir de 16/7/13"

campaign_emails:
  cron: "0 2 * * *"
  class: MarketingUploaderWorker
  queue: low
  args:
    - campaign_emails
    - base_atualizada_emails_promocoes.csv
    - true
  description: "Cria arquivo de importação de emails do lightbox para allinemail"

send_billet_reminder:
  cron: "0 5 * * 1-5"
  class: SendBilletReminderWorker
  queue: low
  description: "Dispara emails de aviso p/ vencimento do boleto"

send_seven_days_to_expiration_warning:
  cron: "40 4 * * *"
  class: SendExpirationWarningWorker
  queue: low
  description: "Dispara emails avisando que os créditos de fidelidade irão expirar"

force_clearsale_callback:
  cron: "*/5 * * * *"
  class: Clearsale::CallbackWorker
  queue: low
  description: "Verifica se o status da avaliação da Clearsale mudou para uma determinada compra (order)"

add_expire_carts_worker:
  cron: "0 0 * * 1"
  class: ExpireCartsWorker
  queue: low
  description: "Expira os Carts sem items com mais de 7 dias toda segunda"

update_mkt_xml_builder:
  cron: "30 3 * * *"
  class: MktXmlBuilderWorker
  queue: low
  description: "Atualiza os xmls"

facebook_friends_list:
  cron: "35 * * * *"
  class: MarketingUploaderWorker
  queue: low
  args:
    - facebook_friends_list
    - facebook_friends-%Y-%m-%d.csv
    - true
    - exact_target.yml
    - 1
  description: "Cria e envia arquivo com base de usuários e amigas aniversariantes para ftp do exact target"

cancel_old_billets:
  cron: "0 12 * * *"
  class: Abacos::CancelExpiredBillet
  queue: low
  description: "Cancela todos os boletos com data de expicacao de um dia antes do ultimo dia util"

cancel_old_mercado_pago:
  cron: "30 12 * * *"
  class: Abacos::CancelExpiredMercadoPagoPayment
  queue: low
  description: "Cancela todos os pagamentos do mercado pago expirados"

gather_blog_posts:
  cron: "0 * * * *"
  class: PostUpdaterWorker
  queue: low
  description: "Atualiza as chamadas dos posts de hora em hora"

clear_leaderboard:
  cron: "0 0 * * 0"
  class: ClearLeaderboardWorker
  queue: low
  description: "Limpa o Ranking de Leaderboard"
