# Stub for running in development
# edit config/rubber/role/resque_worker/resque-pool.yml for production/staging

development:
  "*": 2

staging:
  "*": 2

production:
  "urgent,high,medium,low,calhau": 50
