# Using mail groups is better than personal emails, however Amazon may return
# SMTP error (address blacklisted) for mail groups
settings:
  beginning_working_hour: "08:00:00"
  end_working_hour: "19:00:00"
  purchase_amount_threshold: 69.9
  total_discount_threshold_percent: 50
billet:
  triggers:   
    business_hours: true
    business_days: true
    purchase_amount: true       
  subscribers:
    - joel.silva@olook.com.br
    - regina.souza@olook.com.br
payment_failure:
  triggers:
    business_hours: false
    business_days: false
  subscribers:
    - joel.silva@olook.com.br
    - regina.souza@olook.com.br
fraud_analysis:
  triggers:
    business_hours: false
    business_days: false
    purchase_amount: false
    discount: true
  subscribers:
    - marcelo.azevedo@olook.com.br
    - joel.silva@olook.com.br

