/sapato: 'Sapatos Femininos'
/roupa: 'Roupas Femininas'
/acessorio: 'Bijuterias - Semi Joia e Bijuterias Finas'
/bolsa: 'Bolsas Femininas'
/marcas: 'Marcas de Roupas'
/marcas/Olook: 'Olook - Roupas Femininas e Sapatos Femininos'
/colecoes: 'Moda Feminina'
/presentes: 'Presente de Natal para Namorada e Dia dos Namorados'
/olooklet: 'Outlet Online - Roupas e Sapatos Femininos '
/como-funciona: 'Como Funciona'
/nossa-essencia: 'Nossa Essencia'
/responsabilidade-social: 'Responsabilidade Social'
/olookmovel: 'Olookmovel'
/olook-na-imprensa: 'Olook na Imprensa'
/prazo-de-entrega: 'Prazo de Entrega'
/termos: 'Termos de Uso'
/privacidade: 'Política de Privacidade'
/devolucoes: 'Política de Troca e Devolução'
/fidelidade: 'Fidelidade'
/afiliados: 'Programa de Afiliados'
/centraldeatendimento: 'Central de Atendimento'
/conta/pedidos: 'Meus pedidos'
/conta/edit: 'Dados Pessoais'
/conta/enderecos: 'Meus Endereços'
/conta/creditos: 'Meus Créditos'
/minha/vitrine: 'Minha vitrine Sapatos e Roupas Femininas'
/stylequiz: 'Style Quiz'
'/meu-estilo': 'Meu estilo'
/criar/vitrine: "Criar Vitrine"
/revenda: "Revenda Roupas Femininas, Sapatos Femininos, Bolsas e Acessórios."
/revenda/confirmacao: 'Confirmação de revenda'
/sacola: 'Minha sacola'
/pagamento/login: 'Pagamento Logar'
/pagamento/new: 'Finalização pagamento'
