---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: resque01
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_scheduler
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-7a3e6313
  image_type: m1.xlarge
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_resque01
  - olook_production_resque
  - olook_production_resque_scheduler
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-184-73-37-158.compute-1.amazonaws.com
  external_ip: 184.73.37.158
  internal_host: ip-10-169-1-14.ec2.internal
  internal_ip: 10.169.1.14
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: resque02
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-f8122796
  image_type: m1.large
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_resque02
  - olook_production_resque
  - olook_production_resque_worker
  - olook_production_collectd
  - olook_production_monit
  - olook_production_newrelic
  external_host: ec2-107-22-120-215.compute-1.amazonaws.com
  external_ip: 107.22.120.215
  internal_host: ip-10-157-42-249.ec2.internal
  internal_ip: 10.157.42.249
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app03
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-c22720a3
  image_type: m1.large
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app03
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-184-72-78-65.compute-1.amazonaws.com
  external_ip: 184.72.78.65
  internal_host: ip-10-29-187-44.ec2.internal
  internal_ip: 10.29.187.44
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app04
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-b6d27bd5
  image_type: m1.large
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app04
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_db
  - olook_production_mysql
  - olook_production_mysql_master
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-23-22-209-228.compute-1.amazonaws.com
  external_ip: 23.22.209.228
  internal_host: ip-10-204-39-46.ec2.internal
  internal_ip: 10.204.39.46
  zone: us-east-1d
  platform: linux
  root_device_type: ebs
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-7232c819
  image_type: m1.large
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app01
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_db
  - olook_production_mysql
  - olook_production_mysql_master
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-54-225-4-240.compute-1.amazonaws.com
  external_ip: 54.225.4.240
  internal_host: ip-10-235-52-153.ec2.internal
  internal_ip: 10.235.52.153
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app02
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  instance_id: i-341ce358
  image_type: m1.large
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app02
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_db
  - olook_production_mysql
  - olook_production_mysql_master
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-54-227-83-39.compute-1.amazonaws.com
  external_ip: 54.227.83.39
  internal_host: ip-10-114-211-154.ec2.internal
  internal_ip: 10.114.211.154
  zone: us-east-1d
  platform: linux
  root_device_type: ebs
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: appruby2
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_slave
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: newrelic
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-c4c48aaf
  image_type: m1.small
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_appruby2
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_db
  - olook_production_mysql
  - olook_production_mysql_slave
  - olook_production_newrelic
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-54-211-194-56.compute-1.amazonaws.com
  external_ip: 54.211.194.56
  internal_host: ip-10-118-123-173.ec2.internal
  internal_ip: 10.118.123.173
  zone: us-east-1d
  platform: linux
  root_device_type: ebs
  provider: aws
- volumes: {}
  static_ips: {}
