---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-8726daf5
  image_type: c1.xlarge
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_app01
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-54-234-9-179.compute-1.amazonaws.com
  external_ip: 54.234.9.179
  internal_host: ip-10-31-207-14.ec2.internal
  internal_ip: 10.31.207.14
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
