---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-6dc6061f
  image_type: c1.xlarge
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app01
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-54-234-126-212.compute-1.amazonaws.com
  external_ip: 54.234.126.212
  internal_host: ip-10-159-25-60.ec2.internal
  internal_ip: 10.159.25.60
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app02
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-c1da1ab3
  image_type: c1.xlarge
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app02
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-54-235-62-100.compute-1.amazonaws.com
  external_ip: 54.235.62.100
  internal_host: ip-10-166-19-229.ec2.internal
  internal_ip: 10.166.19.229
  zone: us-east-1d
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app03
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-7921e20b
  image_type: c1.xlarge
  image_id: ami-3fec7956
  security_groups:
  - olook_production_default
  - olook_production_web
  - olook_production_app03
  - olook_production_app
  - olook_production_unicorn
  - olook_production_nginx
  - olook_production_collectd
  - olook_production_monit
  external_host: ec2-107-22-77-105.compute-1.amazonaws.com
  external_ip: 107.22.77.105
  internal_host: ip-10-168-6-7.ec2.internal
  internal_ip: 10.168.6.7
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
