---
- !ruby/object:Rubber::Configuration::InstanceItem
  domain: olook.com.br
  external_host: ec2-54-224-45-237.compute-1.amazonaws.com
  external_ip: 54.224.45.237
  image_id: ami-3fec7956
  image_type: c1.medium
  instance_id: i-394a4356
  internal_host: ip-10-28-6-36.ec2.internal
  internal_ip: 10.28.6.36
  name: development
  platform: linux
  provider: aws
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: memcached
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_scheduler
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  root_device_type: ebs
  security_groups:
  - olook_staging_default
  - olook_staging_web
  - olook_staging_development
  - olook_staging_app
  - olook_staging_unicorn
  - olook_staging_nginx
  - olook_staging_db
  - olook_staging_mysql
  - olook_staging_mysql_master
  - olook_staging_memcached
  - olook_staging_redis
  - olook_staging_resque
  - olook_staging_resque_scheduler
  - olook_staging_resque_worker
  - olook_staging_common
  - olook_staging_collectd
  - olook_staging_monit
  - olook_staging_newrelic
  - olook_staging_redis_master
  zone: us-east-1b
- !ruby/object:Rubber::Configuration::InstanceItem
  domain: olook.com.br
  external_host: ec2-54-224-184-120.compute-1.amazonaws.com
  external_ip: 54.224.184.120
  image_id: ami-3fec7956
  image_type: m1.medium
  instance_id: i-a21bd1c9
  internal_host: ip-10-232-54-171.ec2.internal
  internal_ip: 10.232.54.171
  name: stage
  platform: linux
  provider: aws
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: memcached
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  root_device_type: ebs
  security_groups:
  - olook_staging_default
  - olook_staging_web
  - olook_staging_stage
  - olook_staging_app
  - olook_staging_unicorn
  - olook_staging_nginx
  - olook_staging_db
  - olook_staging_mysql
  - olook_staging_mysql_master
  - olook_staging_memcached
  - olook_staging_redis
  - olook_staging_collectd
  - olook_staging_monit
  zone: us-east-1b
- volumes: {}
  static_ips: {}
