---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: jenkins
  domain: olook.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: jenkins
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-d6a87db3
  image_type: c1.medium
  image_id: ami-3fec7956
  security_groups:
  - olook_jenkins_default
  - olook_jenkins_jenkins_web
  - olook_jenkins_jenkins
  - olook_jenkins_apache
  - olook_jenkins_mysql
  - olook_jenkins_db
  - olook_jenkins_mysql_master
  - olook_jenkins_collectd
  - olook_jenkins_monit
  external_host: ec2-54-224-199-60.compute-1.amazonaws.com
  external_ip: 54.224.199.60
  internal_host: ip-10-29-46-77.ec2.internal
  internal_ip: 10.29.46.77
  zone: us-east-1b
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
